// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mouse_control.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from mouse_control.proto</summary>
public static partial class MouseControlReflection {

  #region Descriptor
  /// <summary>File descriptor for mouse_control.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static MouseControlReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChNtb3VzZV9jb250cm9sLnByb3RvImsKBVN0aWNrEhUKDWNvbnRyb2xfbW91",
          "c2UYAiABKAgSFAoMcmVnaW9uX3N0YXJ0GAMgASgFEg8KB3JlZ2lvbnMYBCAD",
          "KA0SEQoJaW52ZXJ0X3VkGAUgASgIEhEKCWludmVydF9schgGIAEoCCIsCgdU",
          "cmlnZ2VyEhAKCGRlYWR6b25lGAEgASgNEg8KB3JlZ2lvbnMYAiADKA0iowcK",
          "DEJhc2ljQ29udHJvbBIaCgpsZWZ0X3N0aWNrGAEgASgLMgYuU3RpY2sSGwoL",
          "cmlnaHRfc3RpY2sYAiABKAsyBi5TdGljaxIeCgxsZWZ0X3RyaWdnZXIYAyAB",
          "KAsyCC5UcmlnZ2VyEh8KDXJpZ2h0X3RyaWdnZXIYBCABKAsyCC5UcmlnZ2Vy",
          "EjAKCmJ1dHRvbl9tYXAYBSADKAsyHC5CYXNpY0NvbnRyb2wuQnV0dG9uTWFw",
          "RW50cnkSDAoEbmFtZRgGIAEoCRITCgtkZXNjcmlwdGlvbhgHIAEoCRILCgNk",
          "cGkYCCABKA0SEAoIc2xvd19kcGkYCSABKA0SEAoIZmFzdF9kcGkYCiABKA0S",
          "EwoLcmVwZWF0ZGVsYXkYCyABKAQSEwoLcmVwZWF0ZXJhdGUYDCABKAQaXgoH",
          "QWN0aW9ucxIQCghrZXliaW5kcxgBIAMoBRI0Cg9zcGVjaWFsX2FjdGlvbnMY",
          "AiADKA4yGy5CYXNpY0NvbnRyb2wuU3BlY2lhbEFjdGlvbhILCgNleGUYAyAB",
          "KAka9QEKCEJlaGF2aW9yEicKCG9uX3ByZXNzGAEgASgLMhUuQmFzaWNDb250",
          "cm9sLkFjdGlvbnMSFwoPb25fcHJlc3NfdG9nZ2xlGAUgASgIEiYKB29uX2hv",
          "bGQYAiABKAsyFS5CYXNpY0NvbnRyb2wuQWN0aW9ucxIpCgpvbl9yZWxlYXNl",
          "GAMgASgLMhUuQmFzaWNDb250cm9sLkFjdGlvbnMSGQoRb25fcmVsZWFzZV90",
          "b2dnbGUYBiABKAgSJgoHb25fc3RheRgEIAEoCzIVLkJhc2ljQ29udHJvbC5B",
          "Y3Rpb25zEhEKCWJsYWNrbGlzdBgHIAMoBRpICg5CdXR0b25NYXBFbnRyeRIL",
          "CgNrZXkYASABKAUSJQoFdmFsdWUYAiABKAsyFi5CYXNpY0NvbnRyb2wuQmVo",
          "YXZpb3I6AjgBIsYBCg1TcGVjaWFsQWN0aW9uEgwKCE9wZW5NZW51EAASDQoJ",
          "TW91c2VEb3duEAESDQoJTW91c2VMZWZ0EAISDgoKTW91c2VSaWdodBADEgsK",
          "B01vdXNlVXAQBBIOCgpTY3JvbGxEb3duEAkSDgoKU2Nyb2xsTGVmdBAHEg8K",
          "C1Njcm9sbFJpZ2h0EAgSDAoIU2Nyb2xsVXAQChIJCgVUdXJibxAFEhMKD0Vu",
          "dGVyVHlwaW5nTW9kZRAGEg0KCVByZWNpc2lvbhALYgZwcm90bzM="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Stick), global::Stick.Parser, new[]{ "ControlMouse", "RegionStart", "Regions", "InvertUd", "InvertLr" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Trigger), global::Trigger.Parser, new[]{ "Deadzone", "Regions" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BasicControl), global::BasicControl.Parser, new[]{ "LeftStick", "RightStick", "LeftTrigger", "RightTrigger", "ButtonMap", "Name", "Description", "Dpi", "SlowDpi", "FastDpi", "Repeatdelay", "Repeaterate" }, null, new[]{ typeof(global::BasicControl.Types.SpecialAction) }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::BasicControl.Types.Actions), global::BasicControl.Types.Actions.Parser, new[]{ "Keybinds", "SpecialActions", "Exe" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::BasicControl.Types.Behavior), global::BasicControl.Types.Behavior.Parser, new[]{ "OnPress", "OnPressToggle", "OnHold", "OnRelease", "OnReleaseToggle", "OnStay", "Blacklist" }, null, null, null),
          null, })
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Stick : pb::IMessage<Stick> {
  private static readonly pb::MessageParser<Stick> _parser = new pb::MessageParser<Stick>(() => new Stick());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Stick> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MouseControlReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Stick() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Stick(Stick other) : this() {
    controlMouse_ = other.controlMouse_;
    regionStart_ = other.regionStart_;
    regions_ = other.regions_.Clone();
    invertUd_ = other.invertUd_;
    invertLr_ = other.invertLr_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Stick Clone() {
    return new Stick(this);
  }

  /// <summary>Field number for the "control_mouse" field.</summary>
  public const int ControlMouseFieldNumber = 2;
  private bool controlMouse_;
  /// <summary>
  ///uint32 deadzone = 1;//how far must the stick go to count as moved
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool ControlMouse {
    get { return controlMouse_; }
    set {
      controlMouse_ = value;
    }
  }

  /// <summary>Field number for the "region_start" field.</summary>
  public const int RegionStartFieldNumber = 3;
  private int regionStart_;
  /// <summary>
  ///the arc length clockwise from the topmost point of the stick circumference. This is the location of the Center of the 0th region.
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int RegionStart {
    get { return regionStart_; }
    set {
      regionStart_ = value;
    }
  }

  /// <summary>Field number for the "regions" field.</summary>
  public const int RegionsFieldNumber = 4;
  private static readonly pb::FieldCodec<uint> _repeated_regions_codec
      = pb::FieldCodec.ForUInt32(34);
  private readonly pbc::RepeatedField<uint> regions_ = new pbc::RepeatedField<uint>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<uint> Regions {
    get { return regions_; }
  }

  /// <summary>Field number for the "invert_ud" field.</summary>
  public const int InvertUdFieldNumber = 5;
  private bool invertUd_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool InvertUd {
    get { return invertUd_; }
    set {
      invertUd_ = value;
    }
  }

  /// <summary>Field number for the "invert_lr" field.</summary>
  public const int InvertLrFieldNumber = 6;
  private bool invertLr_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool InvertLr {
    get { return invertLr_; }
    set {
      invertLr_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Stick);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Stick other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (ControlMouse != other.ControlMouse) return false;
    if (RegionStart != other.RegionStart) return false;
    if(!regions_.Equals(other.regions_)) return false;
    if (InvertUd != other.InvertUd) return false;
    if (InvertLr != other.InvertLr) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (ControlMouse != false) hash ^= ControlMouse.GetHashCode();
    if (RegionStart != 0) hash ^= RegionStart.GetHashCode();
    hash ^= regions_.GetHashCode();
    if (InvertUd != false) hash ^= InvertUd.GetHashCode();
    if (InvertLr != false) hash ^= InvertLr.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (ControlMouse != false) {
      output.WriteRawTag(16);
      output.WriteBool(ControlMouse);
    }
    if (RegionStart != 0) {
      output.WriteRawTag(24);
      output.WriteInt32(RegionStart);
    }
    regions_.WriteTo(output, _repeated_regions_codec);
    if (InvertUd != false) {
      output.WriteRawTag(40);
      output.WriteBool(InvertUd);
    }
    if (InvertLr != false) {
      output.WriteRawTag(48);
      output.WriteBool(InvertLr);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (ControlMouse != false) {
      size += 1 + 1;
    }
    if (RegionStart != 0) {
      size += 1 + pb::CodedOutputStream.ComputeInt32Size(RegionStart);
    }
    size += regions_.CalculateSize(_repeated_regions_codec);
    if (InvertUd != false) {
      size += 1 + 1;
    }
    if (InvertLr != false) {
      size += 1 + 1;
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Stick other) {
    if (other == null) {
      return;
    }
    if (other.ControlMouse != false) {
      ControlMouse = other.ControlMouse;
    }
    if (other.RegionStart != 0) {
      RegionStart = other.RegionStart;
    }
    regions_.Add(other.regions_);
    if (other.InvertUd != false) {
      InvertUd = other.InvertUd;
    }
    if (other.InvertLr != false) {
      InvertLr = other.InvertLr;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 16: {
          ControlMouse = input.ReadBool();
          break;
        }
        case 24: {
          RegionStart = input.ReadInt32();
          break;
        }
        case 34:
        case 32: {
          regions_.AddEntriesFrom(input, _repeated_regions_codec);
          break;
        }
        case 40: {
          InvertUd = input.ReadBool();
          break;
        }
        case 48: {
          InvertLr = input.ReadBool();
          break;
        }
      }
    }
  }

}

public sealed partial class Trigger : pb::IMessage<Trigger> {
  private static readonly pb::MessageParser<Trigger> _parser = new pb::MessageParser<Trigger>(() => new Trigger());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Trigger> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MouseControlReflection.Descriptor.MessageTypes[1]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Trigger() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Trigger(Trigger other) : this() {
    deadzone_ = other.deadzone_;
    regions_ = other.regions_.Clone();
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Trigger Clone() {
    return new Trigger(this);
  }

  /// <summary>Field number for the "deadzone" field.</summary>
  public const int DeadzoneFieldNumber = 1;
  private uint deadzone_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Deadzone {
    get { return deadzone_; }
    set {
      deadzone_ = value;
    }
  }

  /// <summary>Field number for the "regions" field.</summary>
  public const int RegionsFieldNumber = 2;
  private static readonly pb::FieldCodec<uint> _repeated_regions_codec
      = pb::FieldCodec.ForUInt32(18);
  private readonly pbc::RepeatedField<uint> regions_ = new pbc::RepeatedField<uint>();
  /// <summary>
  ///must add to 255 - deadzone
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<uint> Regions {
    get { return regions_; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Trigger);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Trigger other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (Deadzone != other.Deadzone) return false;
    if(!regions_.Equals(other.regions_)) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (Deadzone != 0) hash ^= Deadzone.GetHashCode();
    hash ^= regions_.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (Deadzone != 0) {
      output.WriteRawTag(8);
      output.WriteUInt32(Deadzone);
    }
    regions_.WriteTo(output, _repeated_regions_codec);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (Deadzone != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Deadzone);
    }
    size += regions_.CalculateSize(_repeated_regions_codec);
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Trigger other) {
    if (other == null) {
      return;
    }
    if (other.Deadzone != 0) {
      Deadzone = other.Deadzone;
    }
    regions_.Add(other.regions_);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 8: {
          Deadzone = input.ReadUInt32();
          break;
        }
        case 18:
        case 16: {
          regions_.AddEntriesFrom(input, _repeated_regions_codec);
          break;
        }
      }
    }
  }

}

public sealed partial class BasicControl : pb::IMessage<BasicControl> {
  private static readonly pb::MessageParser<BasicControl> _parser = new pb::MessageParser<BasicControl>(() => new BasicControl());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<BasicControl> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::MouseControlReflection.Descriptor.MessageTypes[2]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BasicControl() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BasicControl(BasicControl other) : this() {
    LeftStick = other.leftStick_ != null ? other.LeftStick.Clone() : null;
    RightStick = other.rightStick_ != null ? other.RightStick.Clone() : null;
    LeftTrigger = other.leftTrigger_ != null ? other.LeftTrigger.Clone() : null;
    RightTrigger = other.rightTrigger_ != null ? other.RightTrigger.Clone() : null;
    buttonMap_ = other.buttonMap_.Clone();
    name_ = other.name_;
    description_ = other.description_;
    dpi_ = other.dpi_;
    slowDpi_ = other.slowDpi_;
    fastDpi_ = other.fastDpi_;
    repeatdelay_ = other.repeatdelay_;
    repeaterate_ = other.repeaterate_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public BasicControl Clone() {
    return new BasicControl(this);
  }

  /// <summary>Field number for the "left_stick" field.</summary>
  public const int LeftStickFieldNumber = 1;
  private global::Stick leftStick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Stick LeftStick {
    get { return leftStick_; }
    set {
      leftStick_ = value;
    }
  }

  /// <summary>Field number for the "right_stick" field.</summary>
  public const int RightStickFieldNumber = 2;
  private global::Stick rightStick_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Stick RightStick {
    get { return rightStick_; }
    set {
      rightStick_ = value;
    }
  }

  /// <summary>Field number for the "left_trigger" field.</summary>
  public const int LeftTriggerFieldNumber = 3;
  private global::Trigger leftTrigger_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Trigger LeftTrigger {
    get { return leftTrigger_; }
    set {
      leftTrigger_ = value;
    }
  }

  /// <summary>Field number for the "right_trigger" field.</summary>
  public const int RightTriggerFieldNumber = 4;
  private global::Trigger rightTrigger_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Trigger RightTrigger {
    get { return rightTrigger_; }
    set {
      rightTrigger_ = value;
    }
  }

  /// <summary>Field number for the "button_map" field.</summary>
  public const int ButtonMapFieldNumber = 5;
  private static readonly pbc::MapField<int, global::BasicControl.Types.Behavior>.Codec _map_buttonMap_codec
      = new pbc::MapField<int, global::BasicControl.Types.Behavior>.Codec(pb::FieldCodec.ForInt32(8), pb::FieldCodec.ForMessage(18, global::BasicControl.Types.Behavior.Parser), 42);
  private readonly pbc::MapField<int, global::BasicControl.Types.Behavior> buttonMap_ = new pbc::MapField<int, global::BasicControl.Types.Behavior>();
  /// <summary>
  ///use the sharpdx enum for key
  /// </summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::MapField<int, global::BasicControl.Types.Behavior> ButtonMap {
    get { return buttonMap_; }
  }

  /// <summary>Field number for the "name" field.</summary>
  public const int NameFieldNumber = 6;
  private string name_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Name {
    get { return name_; }
    set {
      name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "description" field.</summary>
  public const int DescriptionFieldNumber = 7;
  private string description_ = "";
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public string Description {
    get { return description_; }
    set {
      description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
    }
  }

  /// <summary>Field number for the "dpi" field.</summary>
  public const int DpiFieldNumber = 8;
  private uint dpi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint Dpi {
    get { return dpi_; }
    set {
      dpi_ = value;
    }
  }

  /// <summary>Field number for the "slow_dpi" field.</summary>
  public const int SlowDpiFieldNumber = 9;
  private uint slowDpi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint SlowDpi {
    get { return slowDpi_; }
    set {
      slowDpi_ = value;
    }
  }

  /// <summary>Field number for the "fast_dpi" field.</summary>
  public const int FastDpiFieldNumber = 10;
  private uint fastDpi_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public uint FastDpi {
    get { return fastDpi_; }
    set {
      fastDpi_ = value;
    }
  }

  /// <summary>Field number for the "repeatdelay" field.</summary>
  public const int RepeatdelayFieldNumber = 11;
  private ulong repeatdelay_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong Repeatdelay {
    get { return repeatdelay_; }
    set {
      repeatdelay_ = value;
    }
  }

  /// <summary>Field number for the "repeaterate" field.</summary>
  public const int RepeaterateFieldNumber = 12;
  private ulong repeaterate_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public ulong Repeaterate {
    get { return repeaterate_; }
    set {
      repeaterate_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as BasicControl);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(BasicControl other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if (!object.Equals(LeftStick, other.LeftStick)) return false;
    if (!object.Equals(RightStick, other.RightStick)) return false;
    if (!object.Equals(LeftTrigger, other.LeftTrigger)) return false;
    if (!object.Equals(RightTrigger, other.RightTrigger)) return false;
    if (!ButtonMap.Equals(other.ButtonMap)) return false;
    if (Name != other.Name) return false;
    if (Description != other.Description) return false;
    if (Dpi != other.Dpi) return false;
    if (SlowDpi != other.SlowDpi) return false;
    if (FastDpi != other.FastDpi) return false;
    if (Repeatdelay != other.Repeatdelay) return false;
    if (Repeaterate != other.Repeaterate) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    if (leftStick_ != null) hash ^= LeftStick.GetHashCode();
    if (rightStick_ != null) hash ^= RightStick.GetHashCode();
    if (leftTrigger_ != null) hash ^= LeftTrigger.GetHashCode();
    if (rightTrigger_ != null) hash ^= RightTrigger.GetHashCode();
    hash ^= ButtonMap.GetHashCode();
    if (Name.Length != 0) hash ^= Name.GetHashCode();
    if (Description.Length != 0) hash ^= Description.GetHashCode();
    if (Dpi != 0) hash ^= Dpi.GetHashCode();
    if (SlowDpi != 0) hash ^= SlowDpi.GetHashCode();
    if (FastDpi != 0) hash ^= FastDpi.GetHashCode();
    if (Repeatdelay != 0UL) hash ^= Repeatdelay.GetHashCode();
    if (Repeaterate != 0UL) hash ^= Repeaterate.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    if (leftStick_ != null) {
      output.WriteRawTag(10);
      output.WriteMessage(LeftStick);
    }
    if (rightStick_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(RightStick);
    }
    if (leftTrigger_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(LeftTrigger);
    }
    if (rightTrigger_ != null) {
      output.WriteRawTag(34);
      output.WriteMessage(RightTrigger);
    }
    buttonMap_.WriteTo(output, _map_buttonMap_codec);
    if (Name.Length != 0) {
      output.WriteRawTag(50);
      output.WriteString(Name);
    }
    if (Description.Length != 0) {
      output.WriteRawTag(58);
      output.WriteString(Description);
    }
    if (Dpi != 0) {
      output.WriteRawTag(64);
      output.WriteUInt32(Dpi);
    }
    if (SlowDpi != 0) {
      output.WriteRawTag(72);
      output.WriteUInt32(SlowDpi);
    }
    if (FastDpi != 0) {
      output.WriteRawTag(80);
      output.WriteUInt32(FastDpi);
    }
    if (Repeatdelay != 0UL) {
      output.WriteRawTag(88);
      output.WriteUInt64(Repeatdelay);
    }
    if (Repeaterate != 0UL) {
      output.WriteRawTag(96);
      output.WriteUInt64(Repeaterate);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    if (leftStick_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeftStick);
    }
    if (rightStick_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RightStick);
    }
    if (leftTrigger_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(LeftTrigger);
    }
    if (rightTrigger_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(RightTrigger);
    }
    size += buttonMap_.CalculateSize(_map_buttonMap_codec);
    if (Name.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
    }
    if (Description.Length != 0) {
      size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
    }
    if (Dpi != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dpi);
    }
    if (SlowDpi != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SlowDpi);
    }
    if (FastDpi != 0) {
      size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FastDpi);
    }
    if (Repeatdelay != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Repeatdelay);
    }
    if (Repeaterate != 0UL) {
      size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Repeaterate);
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(BasicControl other) {
    if (other == null) {
      return;
    }
    if (other.leftStick_ != null) {
      if (leftStick_ == null) {
        leftStick_ = new global::Stick();
      }
      LeftStick.MergeFrom(other.LeftStick);
    }
    if (other.rightStick_ != null) {
      if (rightStick_ == null) {
        rightStick_ = new global::Stick();
      }
      RightStick.MergeFrom(other.RightStick);
    }
    if (other.leftTrigger_ != null) {
      if (leftTrigger_ == null) {
        leftTrigger_ = new global::Trigger();
      }
      LeftTrigger.MergeFrom(other.LeftTrigger);
    }
    if (other.rightTrigger_ != null) {
      if (rightTrigger_ == null) {
        rightTrigger_ = new global::Trigger();
      }
      RightTrigger.MergeFrom(other.RightTrigger);
    }
    buttonMap_.Add(other.buttonMap_);
    if (other.Name.Length != 0) {
      Name = other.Name;
    }
    if (other.Description.Length != 0) {
      Description = other.Description;
    }
    if (other.Dpi != 0) {
      Dpi = other.Dpi;
    }
    if (other.SlowDpi != 0) {
      SlowDpi = other.SlowDpi;
    }
    if (other.FastDpi != 0) {
      FastDpi = other.FastDpi;
    }
    if (other.Repeatdelay != 0UL) {
      Repeatdelay = other.Repeatdelay;
    }
    if (other.Repeaterate != 0UL) {
      Repeaterate = other.Repeaterate;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          if (leftStick_ == null) {
            leftStick_ = new global::Stick();
          }
          input.ReadMessage(leftStick_);
          break;
        }
        case 18: {
          if (rightStick_ == null) {
            rightStick_ = new global::Stick();
          }
          input.ReadMessage(rightStick_);
          break;
        }
        case 26: {
          if (leftTrigger_ == null) {
            leftTrigger_ = new global::Trigger();
          }
          input.ReadMessage(leftTrigger_);
          break;
        }
        case 34: {
          if (rightTrigger_ == null) {
            rightTrigger_ = new global::Trigger();
          }
          input.ReadMessage(rightTrigger_);
          break;
        }
        case 42: {
          buttonMap_.AddEntriesFrom(input, _map_buttonMap_codec);
          break;
        }
        case 50: {
          Name = input.ReadString();
          break;
        }
        case 58: {
          Description = input.ReadString();
          break;
        }
        case 64: {
          Dpi = input.ReadUInt32();
          break;
        }
        case 72: {
          SlowDpi = input.ReadUInt32();
          break;
        }
        case 80: {
          FastDpi = input.ReadUInt32();
          break;
        }
        case 88: {
          Repeatdelay = input.ReadUInt64();
          break;
        }
        case 96: {
          Repeaterate = input.ReadUInt64();
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the BasicControl message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum SpecialAction {
      [pbr::OriginalName("OpenMenu")] OpenMenu = 0,
      [pbr::OriginalName("MouseDown")] MouseDown = 1,
      [pbr::OriginalName("MouseLeft")] MouseLeft = 2,
      [pbr::OriginalName("MouseRight")] MouseRight = 3,
      [pbr::OriginalName("MouseUp")] MouseUp = 4,
      [pbr::OriginalName("ScrollDown")] ScrollDown = 9,
      [pbr::OriginalName("ScrollLeft")] ScrollLeft = 7,
      [pbr::OriginalName("ScrollRight")] ScrollRight = 8,
      [pbr::OriginalName("ScrollUp")] ScrollUp = 10,
      [pbr::OriginalName("Turbo")] Turbo = 5,
      [pbr::OriginalName("EnterTypingMode")] EnterTypingMode = 6,
      /// <summary>
      ///opposite of turbo
      /// </summary>
      [pbr::OriginalName("Precision")] Precision = 11,
    }

    public sealed partial class Actions : pb::IMessage<Actions> {
      private static readonly pb::MessageParser<Actions> _parser = new pb::MessageParser<Actions>(() => new Actions());
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pb::MessageParser<Actions> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::BasicControl.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Actions() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Actions(Actions other) : this() {
        keybinds_ = other.keybinds_.Clone();
        specialActions_ = other.specialActions_.Clone();
        exe_ = other.exe_;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Actions Clone() {
        return new Actions(this);
      }

      /// <summary>Field number for the "keybinds" field.</summary>
      public const int KeybindsFieldNumber = 1;
      private static readonly pb::FieldCodec<int> _repeated_keybinds_codec
          = pb::FieldCodec.ForInt32(10);
      private readonly pbc::RepeatedField<int> keybinds_ = new pbc::RepeatedField<int>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public pbc::RepeatedField<int> Keybinds {
        get { return keybinds_; }
      }

      /// <summary>Field number for the "special_actions" field.</summary>
      public const int SpecialActionsFieldNumber = 2;
      private static readonly pb::FieldCodec<global::BasicControl.Types.SpecialAction> _repeated_specialActions_codec
          = pb::FieldCodec.ForEnum(18, x => (int) x, x => (global::BasicControl.Types.SpecialAction) x);
      private readonly pbc::RepeatedField<global::BasicControl.Types.SpecialAction> specialActions_ = new pbc::RepeatedField<global::BasicControl.Types.SpecialAction>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public pbc::RepeatedField<global::BasicControl.Types.SpecialAction> SpecialActions {
        get { return specialActions_; }
      }

      /// <summary>Field number for the "exe" field.</summary>
      public const int ExeFieldNumber = 3;
      private string exe_ = "";
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public string Exe {
        get { return exe_; }
        set {
          exe_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override bool Equals(object other) {
        return Equals(other as Actions);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool Equals(Actions other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if(!keybinds_.Equals(other.keybinds_)) return false;
        if(!specialActions_.Equals(other.specialActions_)) return false;
        if (Exe != other.Exe) return false;
        return true;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override int GetHashCode() {
        int hash = 1;
        hash ^= keybinds_.GetHashCode();
        hash ^= specialActions_.GetHashCode();
        if (Exe.Length != 0) hash ^= Exe.GetHashCode();
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void WriteTo(pb::CodedOutputStream output) {
        keybinds_.WriteTo(output, _repeated_keybinds_codec);
        specialActions_.WriteTo(output, _repeated_specialActions_codec);
        if (Exe.Length != 0) {
          output.WriteRawTag(26);
          output.WriteString(Exe);
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public int CalculateSize() {
        int size = 0;
        size += keybinds_.CalculateSize(_repeated_keybinds_codec);
        size += specialActions_.CalculateSize(_repeated_specialActions_codec);
        if (Exe.Length != 0) {
          size += 1 + pb::CodedOutputStream.ComputeStringSize(Exe);
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(Actions other) {
        if (other == null) {
          return;
        }
        keybinds_.Add(other.keybinds_);
        specialActions_.Add(other.specialActions_);
        if (other.Exe.Length != 0) {
          Exe = other.Exe;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(pb::CodedInputStream input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              input.SkipLastField();
              break;
            case 10:
            case 8: {
              keybinds_.AddEntriesFrom(input, _repeated_keybinds_codec);
              break;
            }
            case 18:
            case 16: {
              specialActions_.AddEntriesFrom(input, _repeated_specialActions_codec);
              break;
            }
            case 26: {
              Exe = input.ReadString();
              break;
            }
          }
        }
      }

    }

    public sealed partial class Behavior : pb::IMessage<Behavior> {
      private static readonly pb::MessageParser<Behavior> _parser = new pb::MessageParser<Behavior>(() => new Behavior());
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pb::MessageParser<Behavior> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::BasicControl.Descriptor.NestedTypes[1]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Behavior() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Behavior(Behavior other) : this() {
        OnPress = other.onPress_ != null ? other.OnPress.Clone() : null;
        onPressToggle_ = other.onPressToggle_;
        OnHold = other.onHold_ != null ? other.OnHold.Clone() : null;
        OnRelease = other.onRelease_ != null ? other.OnRelease.Clone() : null;
        onReleaseToggle_ = other.onReleaseToggle_;
        OnStay = other.onStay_ != null ? other.OnStay.Clone() : null;
        blacklist_ = other.blacklist_.Clone();
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Behavior Clone() {
        return new Behavior(this);
      }

      /// <summary>Field number for the "on_press" field.</summary>
      public const int OnPressFieldNumber = 1;
      private global::BasicControl.Types.Actions onPress_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::BasicControl.Types.Actions OnPress {
        get { return onPress_; }
        set {
          onPress_ = value;
        }
      }

      /// <summary>Field number for the "on_press_toggle" field.</summary>
      public const int OnPressToggleFieldNumber = 5;
      private bool onPressToggle_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool OnPressToggle {
        get { return onPressToggle_; }
        set {
          onPressToggle_ = value;
        }
      }

      /// <summary>Field number for the "on_hold" field.</summary>
      public const int OnHoldFieldNumber = 2;
      private global::BasicControl.Types.Actions onHold_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::BasicControl.Types.Actions OnHold {
        get { return onHold_; }
        set {
          onHold_ = value;
        }
      }

      /// <summary>Field number for the "on_release" field.</summary>
      public const int OnReleaseFieldNumber = 3;
      private global::BasicControl.Types.Actions onRelease_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::BasicControl.Types.Actions OnRelease {
        get { return onRelease_; }
        set {
          onRelease_ = value;
        }
      }

      /// <summary>Field number for the "on_release_toggle" field.</summary>
      public const int OnReleaseToggleFieldNumber = 6;
      private bool onReleaseToggle_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool OnReleaseToggle {
        get { return onReleaseToggle_; }
        set {
          onReleaseToggle_ = value;
        }
      }

      /// <summary>Field number for the "on_stay" field.</summary>
      public const int OnStayFieldNumber = 4;
      private global::BasicControl.Types.Actions onStay_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::BasicControl.Types.Actions OnStay {
        get { return onStay_; }
        set {
          onStay_ = value;
        }
      }

      /// <summary>Field number for the "blacklist" field.</summary>
      public const int BlacklistFieldNumber = 7;
      private static readonly pb::FieldCodec<int> _repeated_blacklist_codec
          = pb::FieldCodec.ForInt32(58);
      private readonly pbc::RepeatedField<int> blacklist_ = new pbc::RepeatedField<int>();
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public pbc::RepeatedField<int> Blacklist {
        get { return blacklist_; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override bool Equals(object other) {
        return Equals(other as Behavior);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool Equals(Behavior other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (!object.Equals(OnPress, other.OnPress)) return false;
        if (OnPressToggle != other.OnPressToggle) return false;
        if (!object.Equals(OnHold, other.OnHold)) return false;
        if (!object.Equals(OnRelease, other.OnRelease)) return false;
        if (OnReleaseToggle != other.OnReleaseToggle) return false;
        if (!object.Equals(OnStay, other.OnStay)) return false;
        if(!blacklist_.Equals(other.blacklist_)) return false;
        return true;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override int GetHashCode() {
        int hash = 1;
        if (onPress_ != null) hash ^= OnPress.GetHashCode();
        if (OnPressToggle != false) hash ^= OnPressToggle.GetHashCode();
        if (onHold_ != null) hash ^= OnHold.GetHashCode();
        if (onRelease_ != null) hash ^= OnRelease.GetHashCode();
        if (OnReleaseToggle != false) hash ^= OnReleaseToggle.GetHashCode();
        if (onStay_ != null) hash ^= OnStay.GetHashCode();
        hash ^= blacklist_.GetHashCode();
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void WriteTo(pb::CodedOutputStream output) {
        if (onPress_ != null) {
          output.WriteRawTag(10);
          output.WriteMessage(OnPress);
        }
        if (onHold_ != null) {
          output.WriteRawTag(18);
          output.WriteMessage(OnHold);
        }
        if (onRelease_ != null) {
          output.WriteRawTag(26);
          output.WriteMessage(OnRelease);
        }
        if (onStay_ != null) {
          output.WriteRawTag(34);
          output.WriteMessage(OnStay);
        }
        if (OnPressToggle != false) {
          output.WriteRawTag(40);
          output.WriteBool(OnPressToggle);
        }
        if (OnReleaseToggle != false) {
          output.WriteRawTag(48);
          output.WriteBool(OnReleaseToggle);
        }
        blacklist_.WriteTo(output, _repeated_blacklist_codec);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public int CalculateSize() {
        int size = 0;
        if (onPress_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnPress);
        }
        if (OnPressToggle != false) {
          size += 1 + 1;
        }
        if (onHold_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnHold);
        }
        if (onRelease_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnRelease);
        }
        if (OnReleaseToggle != false) {
          size += 1 + 1;
        }
        if (onStay_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(OnStay);
        }
        size += blacklist_.CalculateSize(_repeated_blacklist_codec);
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(Behavior other) {
        if (other == null) {
          return;
        }
        if (other.onPress_ != null) {
          if (onPress_ == null) {
            onPress_ = new global::BasicControl.Types.Actions();
          }
          OnPress.MergeFrom(other.OnPress);
        }
        if (other.OnPressToggle != false) {
          OnPressToggle = other.OnPressToggle;
        }
        if (other.onHold_ != null) {
          if (onHold_ == null) {
            onHold_ = new global::BasicControl.Types.Actions();
          }
          OnHold.MergeFrom(other.OnHold);
        }
        if (other.onRelease_ != null) {
          if (onRelease_ == null) {
            onRelease_ = new global::BasicControl.Types.Actions();
          }
          OnRelease.MergeFrom(other.OnRelease);
        }
        if (other.OnReleaseToggle != false) {
          OnReleaseToggle = other.OnReleaseToggle;
        }
        if (other.onStay_ != null) {
          if (onStay_ == null) {
            onStay_ = new global::BasicControl.Types.Actions();
          }
          OnStay.MergeFrom(other.OnStay);
        }
        blacklist_.Add(other.blacklist_);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(pb::CodedInputStream input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              input.SkipLastField();
              break;
            case 10: {
              if (onPress_ == null) {
                onPress_ = new global::BasicControl.Types.Actions();
              }
              input.ReadMessage(onPress_);
              break;
            }
            case 18: {
              if (onHold_ == null) {
                onHold_ = new global::BasicControl.Types.Actions();
              }
              input.ReadMessage(onHold_);
              break;
            }
            case 26: {
              if (onRelease_ == null) {
                onRelease_ = new global::BasicControl.Types.Actions();
              }
              input.ReadMessage(onRelease_);
              break;
            }
            case 34: {
              if (onStay_ == null) {
                onStay_ = new global::BasicControl.Types.Actions();
              }
              input.ReadMessage(onStay_);
              break;
            }
            case 40: {
              OnPressToggle = input.ReadBool();
              break;
            }
            case 48: {
              OnReleaseToggle = input.ReadBool();
              break;
            }
            case 58:
            case 56: {
              blacklist_.AddEntriesFrom(input, _repeated_blacklist_codec);
              break;
            }
          }
        }
      }

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
