// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: save_format.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
/// <summary>Holder for reflection information generated from save_format.proto</summary>
public static partial class SaveFormatReflection {

  #region Descriptor
  /// <summary>File descriptor for save_format.proto</summary>
  public static pbr::FileDescriptor Descriptor {
    get { return descriptor; }
  }
  private static pbr::FileDescriptor descriptor;

  static SaveFormatReflection() {
    byte[] descriptorData = global::System.Convert.FromBase64String(
        string.Concat(
          "ChFzYXZlX2Zvcm1hdC5wcm90byLKBwoNQ29uZmlndXJhdGlvbhIxCgpidXR0",
          "b25fbWFwGAEgAygLMh0uQ29uZmlndXJhdGlvbi5CdXR0b25NYXBFbnRyeRIi",
          "CgRMZWZ0GAIgASgLMhQuQ29uZmlndXJhdGlvbi5TdGljaxIjCgVSaWdodBgD",
          "IAEoCzIULkNvbmZpZ3VyYXRpb24uU3RpY2sSFwoPaW52ZXJ0X1VEX21vdXNl",
          "GAQgASgIEhcKD2ludmVydF9MUl9tb3VzZRgFIAEoCBITCgtzZW5zaXRpdml0",
          "eRgGIAEoAhpaCgVTdGljaxIqCgFzGAEgASgOMh8uQ29uZmlndXJhdGlvbi5D",
          "b250cm9sbGVyU3RpY2tzEhEKCXRocmVzaG9sZBgDIAEoAhISCgptb3ZlX21v",
          "dXNlGAIgASgIGkUKB0JpbmRpbmcSKgoBYhgBIAEoDjIfLkNvbmZpZ3VyYXRp",
          "b24uQ29udHJvbGxlckJ1dHRvbhIOCgZhY3RpdmUYAiABKAgaZQoOQnV0dG9u",
          "TWFwRW50cnkSLAoDa2V5GAEgASgOMh8uQ29uZmlndXJhdGlvbi5Db250cm9s",
          "bGVyQnV0dG9uEiUKBXZhbHVlGAIgASgLMhYuQ29uZmlndXJhdGlvbi5CaW5k",
          "aW5nIrgDChBDb250cm9sbGVyQnV0dG9uEggKBE5PTkUQABIGCgJMUxABEgYK",
          "AlJTEAISBgoCTEIQAxIGCgJSQhAEEgYKAkxUEAUSBgoCUlQQBhIFCgFBEAcS",
          "BQoBQhAIEgUKAVgQCRIFCgFZEAoSCAoETUVOVRALEggKBFZJRVcQDBIICgRY",
          "Qk9YEA0SBwoDTFRIEA4SBwoDUlRIEA8SBwoDTFMwEBASBwoDTFMxEBESBwoD",
          "TFMyEBISBwoDTFMzEBMSBwoDTFM0EBQSBwoDTFM1EBUSBwoDTFM2EBYSBwoD",
          "TFM3EBcSBwoDTFM4EBgSBwoDTFM5EBkSBwoDTFNBEBoSBwoDTFNCEBsSBwoD",
          "TFNDEBwSBwoDTFNEEB0SBwoDTFNFEB4SBwoDTFNGEB8SBwoDUlMwECASBwoD",
          "UlMxECESBwoDUlMyECISBwoDUlMzECMSBwoDUlM0ECQSBwoDUlM1ECUSBwoD",
          "UlM2ECYSBwoDUlM3ECcSBwoDUlM4ECgSBwoDUlM5ECkSBwoDUlNBECoSBwoD",
          "UlNCECsSBwoDUlNDECwSBwoDUlNEEC0SBwoDUlNFEC4SBwoDUlNGEC8iMQoQ",
          "Q29udHJvbGxlclN0aWNrcxINCglMRUZUU1RJQ0sQABIOCgpSSUdIVFNUSUNL",
          "EAFiBnByb3RvMw=="));
    descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
        new pbr::FileDescriptor[] { },
        new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
          new pbr::GeneratedClrTypeInfo(typeof(global::Configuration), global::Configuration.Parser, new[]{ "ButtonMap", "Left", "Right", "InvertUDMouse", "InvertLRMouse", "Sensitivity" }, null, new[]{ typeof(global::Configuration.Types.ControllerButton), typeof(global::Configuration.Types.ControllerSticks) }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Configuration.Types.Stick), global::Configuration.Types.Stick.Parser, new[]{ "S", "Threshold", "MoveMouse" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Configuration.Types.Binding), global::Configuration.Types.Binding.Parser, new[]{ "B", "Active" }, null, null, null),
          new pbr::GeneratedClrTypeInfo(typeof(global::Configuration.Types.ButtonMapEntry), global::Configuration.Types.ButtonMapEntry.Parser, new[]{ "Key", "Value" }, null, null, null)})
        }));
  }
  #endregion

}
#region Messages
public sealed partial class Configuration : pb::IMessage<Configuration> {
  private static readonly pb::MessageParser<Configuration> _parser = new pb::MessageParser<Configuration>(() => new Configuration());
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pb::MessageParser<Configuration> Parser { get { return _parser; } }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static pbr::MessageDescriptor Descriptor {
    get { return global::SaveFormatReflection.Descriptor.MessageTypes[0]; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  pbr::MessageDescriptor pb::IMessage.Descriptor {
    get { return Descriptor; }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Configuration() {
    OnConstruction();
  }

  partial void OnConstruction();

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Configuration(Configuration other) : this() {
    buttonMap_ = other.buttonMap_.Clone();
    Left = other.left_ != null ? other.Left.Clone() : null;
    Right = other.right_ != null ? other.Right.Clone() : null;
    invertUDMouse_ = other.invertUDMouse_;
    invertLRMouse_ = other.invertLRMouse_;
    sensitivity_ = other.sensitivity_;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public Configuration Clone() {
    return new Configuration(this);
  }

  /// <summary>Field number for the "button_map" field.</summary>
  public const int ButtonMapFieldNumber = 1;
  private static readonly pb::FieldCodec<global::Configuration.Types.ButtonMapEntry> _repeated_buttonMap_codec
      = pb::FieldCodec.ForMessage(10, global::Configuration.Types.ButtonMapEntry.Parser);
  private readonly pbc::RepeatedField<global::Configuration.Types.ButtonMapEntry> buttonMap_ = new pbc::RepeatedField<global::Configuration.Types.ButtonMapEntry>();
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public pbc::RepeatedField<global::Configuration.Types.ButtonMapEntry> ButtonMap {
    get { return buttonMap_; }
  }

  /// <summary>Field number for the "Left" field.</summary>
  public const int LeftFieldNumber = 2;
  private global::Configuration.Types.Stick left_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Configuration.Types.Stick Left {
    get { return left_; }
    set {
      left_ = value;
    }
  }

  /// <summary>Field number for the "Right" field.</summary>
  public const int RightFieldNumber = 3;
  private global::Configuration.Types.Stick right_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public global::Configuration.Types.Stick Right {
    get { return right_; }
    set {
      right_ = value;
    }
  }

  /// <summary>Field number for the "invert_UD_mouse" field.</summary>
  public const int InvertUDMouseFieldNumber = 4;
  private bool invertUDMouse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool InvertUDMouse {
    get { return invertUDMouse_; }
    set {
      invertUDMouse_ = value;
    }
  }

  /// <summary>Field number for the "invert_LR_mouse" field.</summary>
  public const int InvertLRMouseFieldNumber = 5;
  private bool invertLRMouse_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool InvertLRMouse {
    get { return invertLRMouse_; }
    set {
      invertLRMouse_ = value;
    }
  }

  /// <summary>Field number for the "sensitivity" field.</summary>
  public const int SensitivityFieldNumber = 6;
  private float sensitivity_;
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public float Sensitivity {
    get { return sensitivity_; }
    set {
      sensitivity_ = value;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override bool Equals(object other) {
    return Equals(other as Configuration);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public bool Equals(Configuration other) {
    if (ReferenceEquals(other, null)) {
      return false;
    }
    if (ReferenceEquals(other, this)) {
      return true;
    }
    if(!buttonMap_.Equals(other.buttonMap_)) return false;
    if (!object.Equals(Left, other.Left)) return false;
    if (!object.Equals(Right, other.Right)) return false;
    if (InvertUDMouse != other.InvertUDMouse) return false;
    if (InvertLRMouse != other.InvertLRMouse) return false;
    if (Sensitivity != other.Sensitivity) return false;
    return true;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override int GetHashCode() {
    int hash = 1;
    hash ^= buttonMap_.GetHashCode();
    if (left_ != null) hash ^= Left.GetHashCode();
    if (right_ != null) hash ^= Right.GetHashCode();
    if (InvertUDMouse != false) hash ^= InvertUDMouse.GetHashCode();
    if (InvertLRMouse != false) hash ^= InvertLRMouse.GetHashCode();
    if (Sensitivity != 0F) hash ^= Sensitivity.GetHashCode();
    return hash;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public override string ToString() {
    return pb::JsonFormatter.ToDiagnosticString(this);
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void WriteTo(pb::CodedOutputStream output) {
    buttonMap_.WriteTo(output, _repeated_buttonMap_codec);
    if (left_ != null) {
      output.WriteRawTag(18);
      output.WriteMessage(Left);
    }
    if (right_ != null) {
      output.WriteRawTag(26);
      output.WriteMessage(Right);
    }
    if (InvertUDMouse != false) {
      output.WriteRawTag(32);
      output.WriteBool(InvertUDMouse);
    }
    if (InvertLRMouse != false) {
      output.WriteRawTag(40);
      output.WriteBool(InvertLRMouse);
    }
    if (Sensitivity != 0F) {
      output.WriteRawTag(53);
      output.WriteFloat(Sensitivity);
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public int CalculateSize() {
    int size = 0;
    size += buttonMap_.CalculateSize(_repeated_buttonMap_codec);
    if (left_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Left);
    }
    if (right_ != null) {
      size += 1 + pb::CodedOutputStream.ComputeMessageSize(Right);
    }
    if (InvertUDMouse != false) {
      size += 1 + 1;
    }
    if (InvertLRMouse != false) {
      size += 1 + 1;
    }
    if (Sensitivity != 0F) {
      size += 1 + 4;
    }
    return size;
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(Configuration other) {
    if (other == null) {
      return;
    }
    buttonMap_.Add(other.buttonMap_);
    if (other.left_ != null) {
      if (left_ == null) {
        left_ = new global::Configuration.Types.Stick();
      }
      Left.MergeFrom(other.Left);
    }
    if (other.right_ != null) {
      if (right_ == null) {
        right_ = new global::Configuration.Types.Stick();
      }
      Right.MergeFrom(other.Right);
    }
    if (other.InvertUDMouse != false) {
      InvertUDMouse = other.InvertUDMouse;
    }
    if (other.InvertLRMouse != false) {
      InvertLRMouse = other.InvertLRMouse;
    }
    if (other.Sensitivity != 0F) {
      Sensitivity = other.Sensitivity;
    }
  }

  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public void MergeFrom(pb::CodedInputStream input) {
    uint tag;
    while ((tag = input.ReadTag()) != 0) {
      switch(tag) {
        default:
          input.SkipLastField();
          break;
        case 10: {
          buttonMap_.AddEntriesFrom(input, _repeated_buttonMap_codec);
          break;
        }
        case 18: {
          if (left_ == null) {
            left_ = new global::Configuration.Types.Stick();
          }
          input.ReadMessage(left_);
          break;
        }
        case 26: {
          if (right_ == null) {
            right_ = new global::Configuration.Types.Stick();
          }
          input.ReadMessage(right_);
          break;
        }
        case 32: {
          InvertUDMouse = input.ReadBool();
          break;
        }
        case 40: {
          InvertLRMouse = input.ReadBool();
          break;
        }
        case 53: {
          Sensitivity = input.ReadFloat();
          break;
        }
      }
    }
  }

  #region Nested types
  /// <summary>Container for nested types declared in the Configuration message type.</summary>
  [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
  public static partial class Types {
    public enum ControllerButton {
      [pbr::OriginalName("NONE")] None = 0,
      /// <summary>
      /// Stick Press
      /// </summary>
      [pbr::OriginalName("LS")] Ls = 1,
      [pbr::OriginalName("RS")] Rs = 2,
      /// <summary>
      /// Bumper
      /// </summary>
      [pbr::OriginalName("LB")] Lb = 3,
      [pbr::OriginalName("RB")] Rb = 4,
      /// <summary>
      /// Trigger
      /// </summary>
      [pbr::OriginalName("LT")] Lt = 5,
      [pbr::OriginalName("RT")] Rt = 6,
      [pbr::OriginalName("A")] A = 7,
      [pbr::OriginalName("B")] B = 8,
      [pbr::OriginalName("X")] X = 9,
      [pbr::OriginalName("Y")] Y = 10,
      [pbr::OriginalName("MENU")] Menu = 11,
      [pbr::OriginalName("VIEW")] View = 12,
      [pbr::OriginalName("XBOX")] Xbox = 13,
      /// <summary>
      /// half trigger pull
      /// </summary>
      [pbr::OriginalName("LTH")] Lth = 14,
      [pbr::OriginalName("RTH")] Rth = 15,
      /// <summary>
      /// Stick Regions
      /// </summary>
      [pbr::OriginalName("LS0")] Ls0 = 16,
      [pbr::OriginalName("LS1")] Ls1 = 17,
      [pbr::OriginalName("LS2")] Ls2 = 18,
      [pbr::OriginalName("LS3")] Ls3 = 19,
      [pbr::OriginalName("LS4")] Ls4 = 20,
      [pbr::OriginalName("LS5")] Ls5 = 21,
      [pbr::OriginalName("LS6")] Ls6 = 22,
      [pbr::OriginalName("LS7")] Ls7 = 23,
      [pbr::OriginalName("LS8")] Ls8 = 24,
      [pbr::OriginalName("LS9")] Ls9 = 25,
      [pbr::OriginalName("LSA")] Lsa = 26,
      [pbr::OriginalName("LSB")] Lsb = 27,
      [pbr::OriginalName("LSC")] Lsc = 28,
      [pbr::OriginalName("LSD")] Lsd = 29,
      [pbr::OriginalName("LSE")] Lse = 30,
      [pbr::OriginalName("LSF")] Lsf = 31,
      [pbr::OriginalName("RS0")] Rs0 = 32,
      [pbr::OriginalName("RS1")] Rs1 = 33,
      [pbr::OriginalName("RS2")] Rs2 = 34,
      [pbr::OriginalName("RS3")] Rs3 = 35,
      [pbr::OriginalName("RS4")] Rs4 = 36,
      [pbr::OriginalName("RS5")] Rs5 = 37,
      [pbr::OriginalName("RS6")] Rs6 = 38,
      [pbr::OriginalName("RS7")] Rs7 = 39,
      [pbr::OriginalName("RS8")] Rs8 = 40,
      [pbr::OriginalName("RS9")] Rs9 = 41,
      [pbr::OriginalName("RSA")] Rsa = 42,
      [pbr::OriginalName("RSB")] Rsb = 43,
      [pbr::OriginalName("RSC")] Rsc = 44,
      [pbr::OriginalName("RSD")] Rsd = 45,
      [pbr::OriginalName("RSE")] Rse = 46,
      [pbr::OriginalName("RSF")] Rsf = 47,
    }

    public enum ControllerSticks {
      [pbr::OriginalName("LEFTSTICK")] Leftstick = 0,
      [pbr::OriginalName("RIGHTSTICK")] Rightstick = 1,
    }

    public sealed partial class Stick : pb::IMessage<Stick> {
      private static readonly pb::MessageParser<Stick> _parser = new pb::MessageParser<Stick>(() => new Stick());
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pb::MessageParser<Stick> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::Configuration.Descriptor.NestedTypes[0]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Stick() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Stick(Stick other) : this() {
        s_ = other.s_;
        threshold_ = other.threshold_;
        moveMouse_ = other.moveMouse_;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Stick Clone() {
        return new Stick(this);
      }

      /// <summary>Field number for the "s" field.</summary>
      public const int SFieldNumber = 1;
      private global::Configuration.Types.ControllerSticks s_ = 0;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::Configuration.Types.ControllerSticks S {
        get { return s_; }
        set {
          s_ = value;
        }
      }

      /// <summary>Field number for the "threshold" field.</summary>
      public const int ThresholdFieldNumber = 3;
      private float threshold_;
      /// <summary>
      /// how far must the stick go to count as moved
      /// </summary>
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public float Threshold {
        get { return threshold_; }
        set {
          threshold_ = value;
        }
      }

      /// <summary>Field number for the "move_mouse" field.</summary>
      public const int MoveMouseFieldNumber = 2;
      private bool moveMouse_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool MoveMouse {
        get { return moveMouse_; }
        set {
          moveMouse_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override bool Equals(object other) {
        return Equals(other as Stick);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool Equals(Stick other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (S != other.S) return false;
        if (Threshold != other.Threshold) return false;
        if (MoveMouse != other.MoveMouse) return false;
        return true;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override int GetHashCode() {
        int hash = 1;
        if (S != 0) hash ^= S.GetHashCode();
        if (Threshold != 0F) hash ^= Threshold.GetHashCode();
        if (MoveMouse != false) hash ^= MoveMouse.GetHashCode();
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void WriteTo(pb::CodedOutputStream output) {
        if (S != 0) {
          output.WriteRawTag(8);
          output.WriteEnum((int) S);
        }
        if (MoveMouse != false) {
          output.WriteRawTag(16);
          output.WriteBool(MoveMouse);
        }
        if (Threshold != 0F) {
          output.WriteRawTag(29);
          output.WriteFloat(Threshold);
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public int CalculateSize() {
        int size = 0;
        if (S != 0) {
          size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) S);
        }
        if (Threshold != 0F) {
          size += 1 + 4;
        }
        if (MoveMouse != false) {
          size += 1 + 1;
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(Stick other) {
        if (other == null) {
          return;
        }
        if (other.S != 0) {
          S = other.S;
        }
        if (other.Threshold != 0F) {
          Threshold = other.Threshold;
        }
        if (other.MoveMouse != false) {
          MoveMouse = other.MoveMouse;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(pb::CodedInputStream input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              input.SkipLastField();
              break;
            case 8: {
              s_ = (global::Configuration.Types.ControllerSticks) input.ReadEnum();
              break;
            }
            case 16: {
              MoveMouse = input.ReadBool();
              break;
            }
            case 29: {
              Threshold = input.ReadFloat();
              break;
            }
          }
        }
      }

    }

    public sealed partial class Binding : pb::IMessage<Binding> {
      private static readonly pb::MessageParser<Binding> _parser = new pb::MessageParser<Binding>(() => new Binding());
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pb::MessageParser<Binding> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::Configuration.Descriptor.NestedTypes[1]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Binding() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Binding(Binding other) : this() {
        b_ = other.b_;
        active_ = other.active_;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public Binding Clone() {
        return new Binding(this);
      }

      /// <summary>Field number for the "b" field.</summary>
      public const int BFieldNumber = 1;
      private global::Configuration.Types.ControllerButton b_ = 0;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::Configuration.Types.ControllerButton B {
        get { return b_; }
        set {
          b_ = value;
        }
      }

      /// <summary>Field number for the "active" field.</summary>
      public const int ActiveFieldNumber = 2;
      private bool active_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool Active {
        get { return active_; }
        set {
          active_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override bool Equals(object other) {
        return Equals(other as Binding);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool Equals(Binding other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (B != other.B) return false;
        if (Active != other.Active) return false;
        return true;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override int GetHashCode() {
        int hash = 1;
        if (B != 0) hash ^= B.GetHashCode();
        if (Active != false) hash ^= Active.GetHashCode();
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void WriteTo(pb::CodedOutputStream output) {
        if (B != 0) {
          output.WriteRawTag(8);
          output.WriteEnum((int) B);
        }
        if (Active != false) {
          output.WriteRawTag(16);
          output.WriteBool(Active);
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public int CalculateSize() {
        int size = 0;
        if (B != 0) {
          size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) B);
        }
        if (Active != false) {
          size += 1 + 1;
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(Binding other) {
        if (other == null) {
          return;
        }
        if (other.B != 0) {
          B = other.B;
        }
        if (other.Active != false) {
          Active = other.Active;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(pb::CodedInputStream input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              input.SkipLastField();
              break;
            case 8: {
              b_ = (global::Configuration.Types.ControllerButton) input.ReadEnum();
              break;
            }
            case 16: {
              Active = input.ReadBool();
              break;
            }
          }
        }
      }

    }

    /// <summary>
    /// map&lt;ControllerButton,Binding> ButtonMap = 1;
    /// compiler doesn't let enum's be keys
    /// </summary>
    public sealed partial class ButtonMapEntry : pb::IMessage<ButtonMapEntry> {
      private static readonly pb::MessageParser<ButtonMapEntry> _parser = new pb::MessageParser<ButtonMapEntry>(() => new ButtonMapEntry());
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pb::MessageParser<ButtonMapEntry> Parser { get { return _parser; } }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public static pbr::MessageDescriptor Descriptor {
        get { return global::Configuration.Descriptor.NestedTypes[2]; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      pbr::MessageDescriptor pb::IMessage.Descriptor {
        get { return Descriptor; }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public ButtonMapEntry() {
        OnConstruction();
      }

      partial void OnConstruction();

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public ButtonMapEntry(ButtonMapEntry other) : this() {
        key_ = other.key_;
        Value = other.value_ != null ? other.Value.Clone() : null;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public ButtonMapEntry Clone() {
        return new ButtonMapEntry(this);
      }

      /// <summary>Field number for the "key" field.</summary>
      public const int KeyFieldNumber = 1;
      private global::Configuration.Types.ControllerButton key_ = 0;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::Configuration.Types.ControllerButton Key {
        get { return key_; }
        set {
          key_ = value;
        }
      }

      /// <summary>Field number for the "value" field.</summary>
      public const int ValueFieldNumber = 2;
      private global::Configuration.Types.Binding value_;
      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public global::Configuration.Types.Binding Value {
        get { return value_; }
        set {
          value_ = value;
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override bool Equals(object other) {
        return Equals(other as ButtonMapEntry);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public bool Equals(ButtonMapEntry other) {
        if (ReferenceEquals(other, null)) {
          return false;
        }
        if (ReferenceEquals(other, this)) {
          return true;
        }
        if (Key != other.Key) return false;
        if (!object.Equals(Value, other.Value)) return false;
        return true;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override int GetHashCode() {
        int hash = 1;
        if (Key != 0) hash ^= Key.GetHashCode();
        if (value_ != null) hash ^= Value.GetHashCode();
        return hash;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public override string ToString() {
        return pb::JsonFormatter.ToDiagnosticString(this);
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void WriteTo(pb::CodedOutputStream output) {
        if (Key != 0) {
          output.WriteRawTag(8);
          output.WriteEnum((int) Key);
        }
        if (value_ != null) {
          output.WriteRawTag(18);
          output.WriteMessage(Value);
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public int CalculateSize() {
        int size = 0;
        if (Key != 0) {
          size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Key);
        }
        if (value_ != null) {
          size += 1 + pb::CodedOutputStream.ComputeMessageSize(Value);
        }
        return size;
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(ButtonMapEntry other) {
        if (other == null) {
          return;
        }
        if (other.Key != 0) {
          Key = other.Key;
        }
        if (other.value_ != null) {
          if (value_ == null) {
            value_ = new global::Configuration.Types.Binding();
          }
          Value.MergeFrom(other.Value);
        }
      }

      [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
      public void MergeFrom(pb::CodedInputStream input) {
        uint tag;
        while ((tag = input.ReadTag()) != 0) {
          switch(tag) {
            default:
              input.SkipLastField();
              break;
            case 8: {
              key_ = (global::Configuration.Types.ControllerButton) input.ReadEnum();
              break;
            }
            case 18: {
              if (value_ == null) {
                value_ = new global::Configuration.Types.Binding();
              }
              input.ReadMessage(value_);
              break;
            }
          }
        }
      }

    }

  }
  #endregion

}

#endregion


#endregion Designer generated code
